### ISSUE TITLE
Initial version testing

### ISSUE THREAD

**Issue by Eloston** [ungoogled-software/ungoogled-chromium-portablelinux#1]
The code in this repo is ready to test. Please try it out and let us know how it goes.

**Comment by anchev** [comment]
The README.md says :
```
git checkout --recurse-submodules TAG_OR_BRANCH_HERE
```
Currently there are no tags. What should one do?

So far I have been building portable linux UC with a simple bash script shared [here](https://github.com/Eloston/ungoogled-chromium/issues/447#issuecomment-422958840). Suddenly after all the recent changes I really don't know what to do - neither my script works, nor I can follow the instructions as discussed here and [in another issue](https://github.com/Eloston/ungoogled-chromium/issues/717).

I hope you can clarify the docs.

**Comment by Eloston** [comment]
There are no tags because there are no releases yet. So, you can use the branch `master` to test.

**Comment by anchev** [comment]
Thanks. `build.sh` throws some error:
```
[...]
INFO: * Applying no-new-ninja-flag.patch (23/27)
DEBUG: /usr/bin/patch -p1 --ignore-whitespace -i /tmp/download/ungoogled-chromium-portablelinux/patches/ubuntu/no-new-ninja-flag.patch -d /tmp/download/ungoogled-chromium-portablelinux/build/src --no-backup-if-mismatch --forward
patching file tools/gn/bootstrap/bootstrap.py
Hunk #1 FAILED at 81.
1 out of 1 hunk FAILED -- saving rejects to file tools/gn/bootstrap/bootstrap.py.rej
Traceback (most recent call last):
  File "/tmp/download/ungoogled-chromium-portablelinux/ungoogled-chromium/utils/patches.py", line 162, in <module>
    main()
  File "/tmp/download/ungoogled-chromium-portablelinux/ungoogled-chromium/utils/patches.py", line 158, in main
    args.callback(args)
  File "/tmp/download/ungoogled-chromium-portablelinux/ungoogled-chromium/utils/patches.py", line 116, in _apply_callback
    patch_bin_path=args.patch_bin)
  File "/tmp/download/ungoogled-chromium-portablelinux/ungoogled-chromium/utils/patches.py", line 54, in apply_patches
    subprocess.run(cmd, check=True)
  File "/usr/lib64/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/patch', '-p1', '--ignore-whitespace', '-i', '/tmp/download/ungoogled-chromium-portablelinux/patches/ubuntu/no-new-ninja-flag.patch', '-d', '/tmp/download/ungoogled-chromium-portablelinux/build/src', '--no-backup-if-mismatch', '--forward']' returned non-zero exit status 1.
```

Here is the full output of all commands:

https://susepaste.org/view//8105983d

**Comment by Eloston** [comment]
Should be fixed in 94d0e113e43707bf8b6802e91e3fc8310f7047c4

**Comment by anchev** [comment]
Thanks. Now it is failing at patch 27:

https://susepaste.org/view//b3c773cc

**Comment by Eloston** [comment]
431ba376a67a9a768c9751938ec32aec1bee2f40

**Comment by anchev** [comment]
Thank you! `ninja` is running fine for now (`[3723/19518]`) with only one error (IIRC discussed before to be harmless):
```
[227/19518] ACTION //chrome/test/chromedriv...p(//build/toolchain/linux/unbundle:default)
ERROR:root:Git error: rc=0, output=''
```
I will write again if I find any other issues.

**Comment by anchev** [comment]
I had more time to let that build today and I can confirm that the building process works fine now.

**Comment by Eloston** [comment]
Awesome! Will tag a new release now.
