### ISSUE TITLE
build  92.0.4515.159-1.1   failed

### ISSUE THREAD

**Issue by c608345** [ungoogled-software/ungoogled-chromium-portablelinux#109]
OS  debian

git clone --recurse-submodules https://github.com/ungoogled-software/ungoogled-chromium-portablelinux.git
cd ungoogled-chromium-portablelinux
git checkout --recurse-submodules 92.0.4515.159-1.1
./build.sh

FAILED: brotli
python3 "../../build/toolchain/gcc_link_wrapper.py" --output="./brotli" -- clang++ -fuse-ld=lld -Wl,--build-id=sha1 -fPIC -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,-z,defs -Wl,--as-needed -Wl,--icf=all -Wl,--color-diagnostics -Wl,-mllvm,-instcombine-lower-dbg-declare=0 -flto=thin -Wl,--thinlto-jobs=all -Wl,--thinlto-cache-dir=thinlto-cache -Wl,--thinlto-cache-policy,cache_size=10%:cache_size_bytes=40g:cache_size_files=100000 -Wl,-mllvm,-import-instr-limit=5 -fwhole-program-vtables -Wl,--no-call-graph-profile-sort -m64 -Wl,-O2 -Wl,--gc-sections -rdynamic -nostdlib++ -Wl,--lto-O0 -fsanitize=cfi-vcall -fsanitize=cfi-icall -pie -Wl,--disable-new-dtags -o "./brotli" -Wl,--start-group @"./brotli.rsp" -Wl,--end-group -ldl -lpthread -lrt
ld.lld: error: undefined symbol: BrotliDefaultFreeFunc

<details>
<summary>./build.sh output</summary>

\+ ./out/Default/gn gen out/Default --fail-on-unused-args
Done. Made 16102 targets from 2664 files in 5499ms
\+ ninja -C out/Default chrome chrome_sandbox chromedriver
ninja: Entering directory `out/Default'
[3892/49597] LINK ./brotli
FAILED: brotli 
python3 "../../build/toolchain/gcc_link_wrapper.py" --output="./brotli" -- clang++ -fuse-ld=lld -Wl,--build-id=sha1 -fPIC -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,-z,defs -Wl,--as-needed -Wl,--icf=all -Wl,--color-diagnostics -Wl,-mllvm,-instcombine-lower-dbg-declare=0 -flto=thin -Wl,--thinlto-jobs=all -Wl,--thinlto-cache-dir=thinlto-cache -Wl,--thinlto-cache-policy,cache_size=10\%:cache_size_bytes=40g:cache_size_files=100000 -Wl,-mllvm,-import-instr-limit=5 -fwhole-program-vtables -Wl,--no-call-graph-profile-sort -m64 -Wl,-O2 -Wl,--gc-sections -rdynamic -nostdlib++ -Wl,--lto-O0 -fsanitize=cfi-vcall -fsanitize=cfi-icall -pie -Wl,--disable-new-dtags -o "./brotli" -Wl,--start-group @"./brotli.rsp"  -Wl,--end-group  -ldl -lpthread -lrt
ld.lld: error: undefined symbol: BrotliDefaultFreeFunc
\>\>\> referenced by ld-temp.o
\>\>\>               lto.tmp:(BrotliDefaultFreeFunc.cfi_jt)

ld.lld: error: undefined symbol: BrotliDefaultAllocFunc
\>\>\> referenced by ld-temp.o
\>\>\>               lto.tmp:(BrotliDefaultAllocFunc.cfi_jt)

ld.lld: error: undefined symbol: BrotliEncoderCreateInstance
\>\>\> referenced by brotli.c
\>\>\>               thinlto-cache/Thin-84a984.tmp.o:(main)

ld.lld: error: undefined symbol: BrotliEncoderSetParameter
\>\>\> referenced by brotli.c
\>\>\>               thinlto-cache/Thin-84a984.tmp.o:(main)
\>\>\> referenced by brotli.c
\>\>\>               thinlto-cache/Thin-84a984.tmp.o:(main)
\>\>\> referenced by brotli.c
\>\>\>               thinlto-cache/Thin-84a984.tmp.o:(main)
\>\>\> referenced 1 more times

ld.lld: error: undefined symbol: BrotliEncoderCompressStream
\>\>\> referenced by brotli.c
\>\>\>               thinlto-cache/Thin-84a984.tmp.o:(main)

ld.lld: error: undefined symbol: BrotliEncoderIsFinished
\>\>\> referenced by brotli.c
\>\>\>               thinlto-cache/Thin-84a984.tmp.o:(main)

ld.lld: error: undefined symbol: BrotliEncoderDestroyInstance
\>\>\> referenced by brotli.c
\>\>\>               thinlto-cache/Thin-84a984.tmp.o:(main)

ld.lld: error: undefined symbol: BrotliTransformDictionaryWord
\>\>\> referenced by decode.c
\>\>\>               thinlto-cache/Thin-b3951b.tmp.o:(ProcessCommands)
\>\>\> referenced by decode.c
\>\>\>               thinlto-cache/Thin-b3951b.tmp.o:(SafeProcessCommands)

ld.lld: error: undefined symbol: BrotliGetDictionary
\>\>\> referenced by state.c
\>\>\>               thinlto-cache/Thin-3fa7ee.tmp.o:(BrotliDecoderStateInit)

ld.lld: error: undefined symbol: BrotliGetTransforms
\>\>\> referenced by state.c
\>\>\>               thinlto-cache/Thin-3fa7ee.tmp.o:(BrotliDecoderStateInit)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[3901/49597] ACTION //third_party/blink/renderer/bindings:web_idl_database(//build/toolchain/linux/unbundle:default)
ninja: build stopped: subcommand failed.

</details>

**Comment by Eloston** [comment]
Closing since this is an old version. Please open a new issue if you are still having troubles.
