### ISSUE TITLE
fatal error: 'stddef.h' file not found

### ISSUE THREAD

**Issue by emanruse** [ungoogled-software/ungoogled-chromium-portablelinux#11]
Trying to build latest stable version (75.0.3770.90-1.1) I am getting `fatal error: 'stddef.h' file not found`. More details:

https://susepaste.org/view//e933cd22

I am using the same process and environment which worked fine for previous versions:
```
clang version 9.0.0 (trunk 355786)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/***/builds/llvm-build/bin
Found candidate GCC installation: /usr/lib64/gcc/x86_64-suse-linux/7
Selected GCC installation: /usr/lib64/gcc/x86_64-suse-linux/7
Candidate multilib: .;@m64
Selected multilib: .;@m64
```

What is this due to and how to fix it please?

**Comment by Eloston** [comment]
I can't say for sure. I tested with LLVM 8 from apt.llvm.org, and it built fine. Could you try downgrading to a more stable LLVM?

**Comment by emanruse** [comment]
> Could you try downgrading to a more stable LLVM?

Tried with clang version 8.0.0 (trunk 346299) which has been very very stable for previous builds for a very long time.

At phase [2/20720] CXX obj/base/base_static/base_switches.o it throws a few:

clang++: error: unknown argument: '-fsplit-lto-unit'

and then terminates with:

[5/20720] ACTION //base:base__jumbo_merge(//build/toolchain/linux/unbundle:default)
ninja: build stopped: subcommand failed.

**Comment by emanruse** [comment]
@Eloston

Can you please share your `clang -v` output?

I cannot install from apt.llvm.org because I am not using Debian (or Ubuntu). But I can try building from source the same trunk version which you use.

**Comment by Eloston** [comment]
@emanruse In that case, you might as well build the same revision that Google uses: https://chromium.googlesource.com/chromium/src/+/refs/tags/75.0.3770.100/tools/clang/scripts/update.py#38

**Comment by emanruse** [comment]
@Eloston

OK, I have built from source the same LLVM version:

```
/opt/llvm/bin/clang -v
clang version 9.0.0 (trunk 357692)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/llvm/bin
Found candidate GCC installation: /usr/lib64/gcc/x86_64-suse-linux/7
Selected GCC installation: /usr/lib64/gcc/x86_64-suse-linux/7
Candidate multilib: .;@m64
Selected multilib: .;@m64
```

Now I am getting on steps 2-4/20720:

```
[2/20720] CXX obj/base/base_static/base_switches.o
...
clang++: error: no such file or directory: 'share/cfi_blacklist.txt'
```

Then:

```
[5/20720] ACTION //base:base__jumbo_merge(//build/toolchain/linux/unbundle:default)
ninja: build stopped: subcommand failed.
```

But this file exists:

```
$ find . -name cfi_blacklist.txt
./ungoogled-chromium-portablelinux/build/src/third_party/llvm/compiler-rt/lib/cfi/cfi_blacklist.txt
./ungoogled-chromium-portablelinux/build/src/third_party/llvm/tools/clang/test/Frontend/Inputs/resource_dir_with_cfi_blacklist/share/cfi_blacklist.txt
```

also:

```
$ find /opt/llvm/ -name cfi_blacklist.txt
/opt/llvm/lib/clang/9.0.0/share/cfi_blacklist.txt
```

In your build.sh I am reading a line;
```
# Hack to allow clang to find the default cfi_blacklist.txt
```

Is it possible that the 3 exports after it don't work properly?

**Comment by emanruse** [comment]
After replacing clang-8 with clang the built was successful.

**Comment by Eloston** [comment]
Oops, I accidentally hardcoded the compiler there. `75.0.3770.100-1.2` fixes it, so you can now export `CC`, `CXX`, etc. before running `build.sh` and it will use those variables to determine `-resources-dir`. In addition, I also revised the LLVM installation instructions a little ibt.

**Comment by emanruse** [comment]
> Oops, I accidentally hardcoded the compiler there. `75.0.3770.100-1.2` fixes it, so you can now export `CC`, `CXX`, etc. before running `build.sh` and it will use those variables to determine `-resources-dir`.

Currently I insert manually CFLAGS and CXXFLAGS in the build.sh after the line which says "# You may also set CFLAGS, CPPFLAGS, CXXFLAGS, and LDFLAGS".

If I do the exports before calling build.sh as you suggest - isn't there any danger that they may be overridden somewhere along the lines? (i.e. by other scripts in the overall sequence)

**Comment by Eloston** [comment]
@emanruse No, because scripts and processes invoked by a shell (of common shells) cannot modify any variables of the shell. The only exception is if the shell sources a script, i.e. `source path/to/script` or `. path/to/script` (period followed by path name). Subprocesses cannot modify the shell environment under any circumstance; typically people workaround this by evaluating the stdout of a subprocess as shell code.

Neither of those situations appear before the export commands in `build.sh`, so it's safe.

**Comment by emanruse** [comment]
Thanks for explaining!
