### ISSUE TITLE
95.0.4638.69-1.1 fails to compile on Ubuntu Impish with Clang 13

### ISSUE THREAD

**Issue by maleyva1** [ungoogled-software/ungoogled-chromium-portablelinux#118]
As the title says, 95.0.4638.69-1.1 fails to compile with Clang 13 on Ubuntu Impish. When Clang gets to compiling `../../third_party/breakpad/breakpad/src/client/linux/handler/exception_handler.cc`, compilation fails with `../../third_party/breakpad/breakpad/src/client/linux/handler/exception_handler.cc:141:41: error: no matching function for call to 'max'`

**Comment by antimof** [comment]
I think It's already solved in Debian branch - https://github.com/ungoogled-software/ungoogled-chromium-debian/commit/cbb04322d88a386e3f5b3f6ae89a61922e0f61cb
It would be great to add that patch to portablelinux...

**Comment by maleyva1** [comment]
@antimof Thanks for that. I didn't notice this was fixed in the Debian branch. 

There's a slew of issues aside from this that stops 95.0.4638.69-1.1 from compiling though. After working through it, in order to get 95.0.4638.69-1.1 to compile you'll need to export `LDFLAGS` with the path of Clang's resource directory, apply the specific patches you linked, and patch the ungoogled-chromium.yml. The desktop file isn't present anymore and is now included in the build/src folder as a template. The Debian branch has the patches [here](https://github.com/ungoogled-software/ungoogled-chromium-debian/blob/unified/debian/patches/template-correction.patch).

I would share my changes but seeing as these are already fixed in the Debian branch, I'd wait for those to get merged.

**Comment by mdedonno1337** [comment]
yeaa, impossible as well for me with clang13, and not trivial to port the patches here.
I compile with clang14, seems to work, dont know why.
