### ISSUE TITLE
Ubuntu installation fails with unmet dependencies

### ISSUE THREAD

**Issue by stubkan** [ungoogled-software/ungoogled-chromium-portablelinux#133]
Running Ubuntu Focal on Ubuntu Mint
Installed ungoogled chromium a week ago, it was version 95, had various problems so have come back to reinstall to try to get a newer version...

But the install fails with the following message

The following packages have unmet dependencies:
 ungoogled-chromium : Depends: libc6 (>= 2.32) but 2.31-0ubuntu9.2dso2 is to be installed
                      Depends: libjpeg62-turbo (>= 1:1.5.0) but it is not installable
                      Depends: libjsoncpp24 (>= 1.9.4) but it is not installable
                      Depends: libre2-9 (>= 20201101+dfsg) but it is not installable
                      Depends: libstdc++6 (>= 11) but 10.3.0-1ubuntu1~20.04 is to be installed
                      Depends: libwebpmux3 (>= 0.6.1-2.1) but 0.6.1-2ubuntu0.20.04.1 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by Aufschlauer** [comment]
It seems to be a question related to [ungoogled-chromium-debian](https://github.com/ungoogled-software/ungoogled-chromium-debian).

**Comment by clickot** [comment]
@stubkan  since the current releases run on focal again, may i close this issue?
