### ISSUE TITLE
not in build: chrome://flags/#enable-webrtc-pipewire-capturer 

### ISSUE THREAD

**Issue by ghost** [ungoogled-software/ungoogled-chromium-portablelinux#135]
The chrome://flags/#enable-webrtc-pipewire-capturer flag is not available in the ungoogled-chromium-portable-build, as well as the appimage, both available from [here](https://ungoogled-software.github.io/ungoogled-chromium-binaries/). It is, however, present in the ungoogled-chromium flatpak on flathub, for example. The creator of the portable and appimage binaries [says](https://github.com/clickot/ungoogled-chromium-portable-build/issues/1#issuecomment-1056684051) they take things as they are from here.

As the flag is necessary for screen sharing in Wayland sessions, it would be great if it could be includes at some stage.

**Comment by clickot** [comment]
@ghost  the flag is present at least in the current release (120.xx) and i don't know since when for older releases, so i close this issue.
