### ISSUE TITLE
100.0.4896.127-1.1 for portablelinux can not run with Centos-8

### ISSUE THREAD

**Issue by kirbyzhou** [ungoogled-software/ungoogled-chromium-portablelinux#139]
Download from 
https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/linux_portable/64bit/100.0.4896.127-1

]$ ldd ./chrome | fgrep 'not found'
./chrome: /lib64/libpthread.so.0: version `GLIBC_2.30' not found (required by ./chrome)
./chrome: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by ./chrome)
./chrome: /lib64/libxkbcommon.so.0: version `V_1.0.0' not found (required by ./chrome)

]$ sha1sum ungoogled-chromium_100.0.4896.127-1.1_linux.tar.xz 
b808ada2366a656a15619749cdcd00504cbfff89  ungoogled-chromium_100.0.4896.127-1.1_linux.tar.xz

]$ rpm -q glibc libxkbcommon
glibc-2.28-164.el8.x86_64
libxkbcommon-0.9.1-1.el8.x86_64

]$ cat /etc/redhat-release 
CentOS Linux release 8.5.2111

**Comment by kirbyzhou** [comment]
ungoogled-chromium-portablelinux is compiled under debian:bullseye, it use glibc-2.30.
So the binary can not be used with Centod-7 and Centos-8.
Sadly story.

**Comment by telecran-telecrit** [comment]
> ungoogled-chromium-portablelinux is compiled under debian:bullseye, it use glibc-2.30. So the binary can not be used with Centod-7 and Centos-8. Sadly story.

Just rebuild it.

**Comment by clickot** [comment]
@kirbyzhou afaik CentOS 8 will be EOL in 2024, so is this issue still relevant or may i close it?
