### ISSUE TITLE
package.sh fails to find FILES.cfg

### ISSUE THREAD

**Issue by alexmat** [ungoogled-software/ungoogled-chromium-portablelinux#142]
When I run package.sh, it looks for FILES.cfg in the root directory, but it doesn't exist. I downloaded this one: https://chromium.googlesource.com/chromium/+/refs/heads/trunk/chrome/tools/build/linux/FILES.cfg and it worked

**Comment by pdfrod** [comment]
Apparently this is a known issue: https://github.com/ungoogled-software/ungoogled-chromium-portablelinux/issues/137

For some reason https://github.com/ungoogled-software/ungoogled-chromium-portablelinux/issues/137 was closed, although the fix wasn't merged to this repo yet.
