### ISSUE TITLE
AppImages with spaces in the file name don't run

### ISSUE THREAD

**Issue by tenkuken** [ungoogled-software/ungoogled-chromium-portablelinux#146]
example:
ungoogled-chromium_116.0.5845.179-1.1.AppImage --incognito --user-data-dir="/tmp/testing 1 2 3"

browser will open 3 tabs (1,2,3).

**Comment by networkException** [comment]
Can you try escaping the spaces using backslashes like so?

```
ungoogled-chromium_116.0.5845.179-1.1.AppImage --incognito --user-data-dir=/tmp/testing\ 1\ 2\ 3
```

**Comment by tenkuken** [comment]
not working: wrapper AppImage
ungoogled-chromium_116.0.5845.179-1.1.AppImage --incognito --user-data-dir=/tmp/testing\ 1\ 2\ 3
ungoogled-chromium_116.0.5845.179-1.1.AppImage --incognito --user-data-dir="/tmp/testing\ 1\ 2\ 3"

working: non wrapper AppImage
/ungoogled-chromium-portablelinux/target/src/out/Default/chrome --incognito --user-data-dir=/tmp/testing\ 1\ 2\ 3
/ungoogled-chromium-portablelinux/target/src/out/Default/chrome --incognito --user-data-dir="/tmp/testing\ 1\ 2\ 3"

Reference:
https://github.com/AppImage/AppImageKit/issues/678

**Comment by clickot** [comment]
surrounding passed $@ with double quotes within AppRun script seems to fix this:
 - "${HERE}"/opt/google/chrome/chrome --password-store=basic "$@"
I will try this with the next release

**Comment by clickot** [comment]
@tenkuken could you please check if 117.0.5938.92-1 works for you know?

**Comment by tenkuken** [comment]
> @tenkuken could you please check if 117.0.5938.92-1 works for you know?

it is working perfectly now.
