### ISSUE TITLE
Docker scripts to build portable image

### ISSUE THREAD

**Issue by hrj** [ungoogled-software/ungoogled-chromium-portablelinux#18]
I have created [this project](https://github.com/LiMium/ungoogled-chromium-portable-docker) that contains docker scripts to build a portable image of ungoogled-chromium. It basically just gathers all the dependencies and sets up clang, etc, then calls the scripts from this repo to start the build.

This will simplify the build a lot because:
* the only pre-requisite is `docker`
* works the same on any linux host
* the dependencies don't pollute the host system

Will be more than happy to move the repo to this organisation, if there is interest.

**Comment by Eloston** [comment]
That's nifty. Would it make more sense to add your Docker files to this repo, or are there reasons why they should to be separate?

**Comment by hrj** [comment]
I can see three ways to organize the Docker files in relation to this repo:

#### 1. Separate repos
This repo gets cloned at run-time inside the docker image. The advantage is that the docker image doesn't have to be rebuilt for every change in this repo.

#### 2. Same repo + mount this repo's files inside Docker image
This might be the most optimal from `git` point of view.
Disadvantage is that the docker image needs to be rebuilt for every change in this repo.

#### 3. Same repo  + cloning of this repo inside Docker image
Similar to `1` in theory, but it has this weird recursion going on.

So, it's a "pick your poison" scenario.

**Comment by hrj** [comment]
Wait, I just thought of a 4th variation:

#### 4. Same repo + build first docker stage independently + mount this repo inside second stage

The idea is to build a base docker image with all dependencies. Then define another docker image that is based on the first and mounts this repo's scripts.

The advantage is that the first image will remain mostly constant and can be cached, while only the second stage will get rebuilt. Building the second stage would be very fast, so it wouldn't be a problem at all.

I will work on a patch if `4` sounds good.

**Comment by Eloston** [comment]
`4` sounds good. Looking forward to it :+1:

**Comment by hrj** [comment]
@Eloston So I am trying to build with the latest release (77.x) and getting OOM errors while building.

It looks like jumbo build is enabled. How do I change the file limit for jumbo builds? I tried setting this environment variable `EXTRA_GN=jumbo_file_merge_limit=10`, but it doesn't seem to make any difference.

**Comment by Eloston** [comment]
I haven't heard of the `EXTRA_GN` setting before, though I haven't kept up with the latest GN changes either.

You need to change the flags before the call to `gn gen`. There are two ways to do this:

1. Append it to `flags.portable.gn`
2. Append it to `out/Default/args.gn` after it has been generated by `build.sh`
