### ISSUE TITLE
Consider using sysroot or sysroot scripts inside Docker

### ISSUE THREAD

**Issue by Eloston** [ungoogled-software/ungoogled-chromium-portablelinux#29]
Chromium's sysroot scripts have quite a few modifications to maximize compatibility of their builds (see `HacksAndPatchesCommon` in https://chromium.googlesource.com/chromium/src.git/+/master/build/linux/sysroot_scripts/sysroot-creator.sh). We should include them so we have the same compatibility as official Chrome/Chromium.

There are two ways we could implement this:
1. Modify the Docker environment with these hacks. We may have to reimplement the hacks ourselves in this case.
2. Add another build method that creates a sysroot image and configure GN to use it. It should be possible to add this to `build.sh`, but I don't know how easy that is. It also makes the Docker container a bit redundant.

**Comment by Eloston** [comment]
Discussion welcome on choosing a solution (or finding another one).

**Comment by clickot** [comment]
the sysroot feature is used in the meantime
