### ISSUE TITLE
'Ptrace Protection with Yama LSM' = No in chrome://sandbox/

### ISSUE THREAD

**Issue by anchev** [ungoogled-software/ungoogled-chromium-portablelinux#3]
I notice that `chrome://sandbox/` shows everything equal to Yes except:

Layer 1 Sandbox | Namespace
------------ | -------------
PID namespaces | Yes
Network namespaces | Yes
Seccomp-BPF sandbox | Yes
Seccomp-BPF sandbox supports TSYNC | Yes
**Ptrace Protection with Yama LSM (Broker)** | **No**
**Ptrace Protection with Yama LSM (Non-broker)** | **No**

**You are adequately sandboxed.**
---

I have no idea if the above is an issue that needs fixing or anything to worry about at all. So some feedback would be appreciated.

**Comment by Eloston** [comment]
These are discussed here: https://github.com/Eloston/ungoogled-chromium/issues/519#issuecomment-425315496

From personal experience, I've seen this working on Ubuntu, but not on Debian. I suspect it is due to the kernel config.

**Comment by anchev** [comment]
> I suspect it is due to the kernel config.

What do you mean by that?

**Comment by Eloston** [comment]
I'm suspecting that this difference is in the kernel parameters or the Kconfig that the two distributions use.

**Comment by anchev** [comment]
I have no idea what Kconfig is.

Do you mean the boot parameters or something else?

If the former: which ones are different?

**Comment by Eloston** [comment]
It could be that the kernel boot parameters differ, the configuration used to build the kernel are different, or both differ. I don't know what exact differences cause this.

**Comment by Chexier** [comment]
> I have no idea if the above is an issue that needs fixing or anything to worry about at all. So some feedback would be appreciated.

This is an issue with your kernel configuration. Compile a new kernel with `CONFIG_SECURITY_YAMA=y`.


> It could be that the kernel boot parameters differ, the configuration used to build the kernel are different, or both differ. I don't know what exact differences cause this.

Yes. CONFIG_SECURITY_YAMA=y is set on Ubuntu but not Debian.

Gentoo Linux doesn't have this problem, the user can easily enable this option while compiling the kernel for the first time :)
