### ISSUE TITLE
No space in C(XX/PP)FLAGS exports in build.sh

### ISSUE THREAD

**Issue by emanruse** [ungoogled-software/ungoogled-chromium-portablelinux#36]
I noticed that exporting custom CFLAGS results in concatenation like this (example):
```
CFLAGS='something'
```
While `build.sh` is running this results in:
```
clang++ ... something-resource-dir=...
````
instead of:
```
clang++ ... something -resource-dir=...
```

Of course it is not a problem to workaround this with an extra space in my custom script which adds CFLAGS however it may be better to add it on lines 34-38 in `build.sh`, e.g.:
```
export CFLAGS+=-resource-dir=$("$CC" --print-resource-dir) \
```
becomes
```
export CFLAGS+=' -resource-dir='$("$CC" --print-resource-dir) \
```

BTW why is there a trailing ` \` on all 3 lines?

**Comment by Eloston** [comment]
I built 95.0.4638.54 recently with https://github.com/ungoogled-software/ungoogled-chromium-debian/commit/c4a57c98368c3d8f99366cc10ee692a6a8418c09 and I didn't need to prefix a space for the environment variables. Not sure why you needed to. Let me know if this is still an issue.
