### ISSUE TITLE
How to have up-to-date build?

### ISSUE THREAD

**Issue by nchv** [ungoogled-software/ungoogled-chromium-portablelinux#4]
Now that the version on the main repo has been [updated](https://github.com/Eloston/ungoogled-chromium/commit/c6b4d9bf0b8f463394327a1b4e54689be2a3ac99) - and the general build.md guide cannot be followed without [issues](https://github.com/Eloston/ungoogled-chromium/issues/717#issuecomment-47795493) - what is the right way to have an up-to-date version of portablelinux UC?

**Comment by Eloston** [comment]
Simply, it is to update this repo to use the latest ungoogled-chromium code. As the name suggests, this repo is dedicated exclusively to the Portable Linux "platform" support.

**Comment by Eloston** [comment]
I should also clarify that the rough example is only for users who want to make a custom build that is not supported by any of the existing platform repos (like this one). The main ungoogled-chromium repo no longer contains code for specific platforms.

**Comment by nchv** [comment]
> Simply, it is to update this repo to use the latest ungoogled-chromium code.

Does that mean that the actual issue is that this repo is not "synced" with the main one (which is the latest version)?

To clarify my goal too:
So far I have always been building the (previously known) `linux_portable` and I would like to keep doing it. The recent changes made me remake my build scripts to use this repo. But now that I see it does not match the latest version of Chromium (like the main repo does) I am confused what to do.

**Comment by Eloston** [comment]
Sorry for missing your reply here. Yes, you can think of the repo as being out-of-sync. The GN flags and patches in this repository will need to be updated to consider new changes in the main ungoogled-chromium repo and new changes in Chromium.

**Comment by nchv** [comment]
Thanks.
Looking forward to it :)
