### ISSUE TITLE
Spell check doesn't work in slack for Portable Linux 64-bit	 83.0.4103.97-1.1

### ISSUE THREAD

**Issue by marek141017** [ungoogled-software/ungoogled-chromium-portablelinux#55]
Spell check doesn't work in slack for Portable Linux 64-bit 83.0.4103.97-1.1

Works as expected in Portable Linux 64-bit 71.xxx version 
Tested on Ubuntu 20.04 LTS

Thank you

**Comment by Eloston** [comment]
Closing because issue is old. Let us know if it is still not working.
