### ISSUE TITLE
Deprecated Python Modules Prevent Building

### ISSUE THREAD

**Issue by 4abab** [ungoogled-software/ungoogled-chromium-portablelinux#64]
I cannot build on opensuse tumbleweed currently as several files contain deprecated use of StringIO and cStringIO

`[1061/40414] ACTION //chrome/test/chromedriver:embed_extension_in_cpp(//build/toolchain/linux/unbundle:default)
FAILED: gen/chrome/test/chromedriver/chrome/embedded_automation_extension.cc gen/chrome/test/chromedriver/chrome/embedded_automation_extension.h
python ../../chrome/test/chromedriver/embed_extension_in_cpp.py --directory gen/chrome/test/chromedriver/chrome ../../chrome/test/chromedriver/extension/background.js ../../chrome/test/chromedriver/extension/manifest.json
Traceback (most recent call last):
  File "../../chrome/test/chromedriver/embed_extension_in_cpp.py", line 11, in <module>
    import StringIO
ModuleNotFoundError: No module named 'StringIO'
[1070/40414] ACTION //extensions/common/api:generated_api_json_strings_bundle_generator_schema(//build/toolchain/linux/unbundle:default)
ninja: build stopped: subcommand failed.`

What would be my best course of action to complete a build?
Thanks,

**Comment by wchen342** [comment]
Try using a virtualenv?

**Comment by Eloston** [comment]
StringIO was deprecated in Python 3. You should make sure `python` refers to Python 2 by modifying PATH (e.g. by using a virtualenv).
