### ISSUE TITLE
Update portable to 85.*

### ISSUE THREAD

**Issue by christianitus03** [ungoogled-software/ungoogled-chromium-portablelinux#69]
This binary is still on version 83.0.4103.97-1.1. Could someone update it to at least 85.0.4183.102-1? Portable is from over 3 months ago.

**Comment by Eloston** [comment]
Done with https://github.com/ungoogled-software/ungoogled-chromium-binaries/commit/85ade2ce7ca183c775d52e221527a539da2c320b.
