### ISSUE TITLE
Update to repo and binaries to 87.0.4280.67-1 (or latest)

### ISSUE THREAD

**Issue by christianitus03** [ungoogled-software/ungoogled-chromium-portablelinux#80]
Can a maintainer please update this package to the latest on the main repo? Additionally, the downloadable binary on [https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/linux_portable/64bit/85.0.4183.102-1.1](url) is still on version 85.0.4183.102-1.1. Could someone please update that as well?

**Comment by Eloston** [comment]
Issue was solved sometime before this comment.
