### ISSUE TITLE
Portable Linux 87.0.4280.67-1.1 - Segmentation Fault with v85 settings, Singleton links appear, and output errors

### ISSUE THREAD

**Issue by jlj2** [ungoogled-software/ungoogled-chromium-portablelinux#82]
Portable Linux Ungoogled Chromium ('UC') v87.0.4280.67-1.1, offered by @LordTwix, was installed on Calculate Linux (Gentoo-compatible) 20.6. The following three issues manifested, the last of which is still outstanding (the more up-to-date Portable Linux Ungoogled Chromium version 87.0.4280.88-1.1 offered by @mcstrugs was not tested here):-

1.  Whenever Portable Linux UC v87.0.4280.67-1.1 was launched from a terminal, keeping settings from Portable Linux UC v85, this terminated with a 'Segmentation Fault' when launched from a new `/bin/usr/chromium` soft link, regardless whether it was launched from a new and `--incognito` switch or not, and regardless of the variation of urls specified, if any.  Perhaps the original `~/.config/chromium` settings folder - carried over from UC v85 and probably older versions - became corrupted at one point;  that settings folder had since been used several times lately with the out-of-the-box Calculate-Linux-/Gentoo-provided Chromium v87.0.4280.66 offered on a new system install.  
**Solution** - Ungoogled-Chromium Portable Version 87.0.4280.67-1.1 version opened correctly with a clean UC install:
Step 1) Export bookmarks while running v85 (or other version, perhaps) in the standard way for later import;  
Step 2) Backup the v85 `~/.config/chromium` directory, say, to `~/.config/chromiumV85` for safekeeping in case you later want to revert to v85;  
Step 3) Launch the new Portable Version 87 version, which forces UC to automatically create a new chromium settings folder for this new version.
This works so far.  

2. Therefore, a newly created `~/.config/chromium` directory was created (clean UC install); and bookmarks backed up from v85 were then proceded to be imported.  Freshly-created search engines were entered with freshly-installed extensions for v87 and freshly-specified cookie policies and font settings.  In order to save setup time for other user(s) on this system, this new directory with its settings was attempted to be copied over from the first user to another, and ownership was attributed to, say, 'newuser':
```
sudo chown newuser:newuser -R /home/newuser/.config/chromium
```
 
Although, as expected, no segmentation faults occurred for the user logged in as 'newuser', the following did manifest:-
a) Cookie policies, font settings and v87 extensions at least, as set by the first user, somehow did not carry over despite having being set by the first user in a fresh v87 install and file ownerships having been set for 'newuser'.
b) `SingletonCookie`, `SingletonLock` and `SingletonSocket` were found listed in  of `newuser`'s imported `.config/chromium` v87 directory, copied over chromium from the first user. Those 'Singleton' elements were perhaps simply due to extensions, as mentioned [here](https://unix.stackexchange.com/questions/375489/cant-open-chromium-anymore) and [here](https://github.com/FuckTheWorld/chromedriver/issues/721) (or perhaps see [this](https://www.raspberrypi.org/forums/viewtopic.php?p=1690041) also).  Indeed, the extensions didn't load, nor the settings, although the bookmarks and search engines did carry over.

3. From memory, a few days ago, UC's `chrome-wrapper` launcher in this Linux Portable v87 would hang after launching from a terminal when specifying several websites as parameters (see steps reproduced below from memory).  UC v87 was launched as shown below (with a similar list of urls used as parameters although probably launching by using soft link `/usr/bin/chromium` pointing to `chrome-wrapper` instead), and after several minutes, the UC session was manually attempted to be shut down by clicking the 'x' at the top right of UC's window, but the terminal from which `chrome-wrapper` was launched then did not immediately offer a '$' prompt;  the terminal just 'hung' displaying perhaps no new messages.  I didn't make much deal of it and after a moment I just decided to close the terminal as I didn't get a new prompt.  Today, I could not reproduce this.  I doubt that the `.config/chromium` folder for v85 had still been used, which had caused a hiccup for the v87 session, as in cases 1. and 2. above.  However, when launching UC v87 today with the `.config/chromium` folder deleted (so as to get a clean settings folder generated), UC developers may want to be aware of some error messages that were generated before shutting down UC by clicking the 'x' at the top right of UC's window after just two minutes without clicking on anything in the opened tabs.  EDIT:  I accidentally tried this experiment publishing the results here for UC v85, so I have edited that out and retried the following command twice with v87:

```
$ ./chrome-wrapper 'https://gnews.org/' 'https://nitter.net/CHHR01'  'https://nitter.net/Stars4P'  'https://nitter.net/roccogalatilaw'  'https://nitter.net/Rothbard1776'  'https://nitter.net/SidneyPowell1' 'https://nitter.net/dmills3710'  'https://nitter.net/iNewsTV' 'https://nitter.net/ElizabetCovfefe' 'https://nitter.net/GeorgWebb' 'https://nitter.net/search?f=tweets&q=pufpufpafpaf+lang%3Aen'  'https://nitter.net/anthonyfenton'  'https://nitter.net/frank275'  'https://nitter.net/SaRaAshcraft'  'https://nitter.net/LucindDionysius'  'https://nitter.net/boginjaproleca'  'https://nitter.net/n0nmanifest' 'https://nitter.net/jeffreyprather' 'https://therightscoop.com/' 'https://nitter.net/JuliansRum' 'https://nitter.net/Stars4P' 'https://nitter.net/kraken_wood' 

```
Strangely, the first time I tried to repeat this experiment today by using the following command got partly rehashed, yet a screenshot taken with xfce4-screenshooter somehow only displays a slither (it seems to be a slither of my background wallpaper):-

![github com__Eloston__ungoogled-chromium__issues-PortLin87 0 4280 67-1 1 - Segmentation Fault with v85 settings, Singleton links appear, and four output errors - 9 12 2](https://user-images.githubusercontent.com/17560937/101700932-eb535f80-3a4b-11eb-8fb6-b3002f2f17df.PNG)

Here is the output from that first retrial, and it produced a 'hashed prompt':
```
$ cd /opt/ungoogled-chromium_87.0.4280.67-1.1_linux/
thankGdasuser /opt/ungoogled-chromium_87.0.4280.67-1.1_linux $ ./chrome-wrapper 'https://gnethankGdasuser /opt/ungoogled-chromium_87.0.4280.67-1.1_linux $ ./chrome-wrapper thankGdasuser /opt/ungoogled-chromium_87.0.4280.67-1.1_linux $ ./chrome-wrapper 'https://gnews.org/' 'https://nitter.net/CHHR01'  'https://nitter.net/Stars4P'  'https://nitter.net/roccogalatilaw'  'https://nitter.net/Rothbard1776'  'https://nitter.net/SidneyPowell1' 'https://nitter.net/dmills3710'  'https://nitter.net/iNewsTV' 'https://nitter.net/ElizabetCovfefe' 'https://nitter.net/GeorgWebb' 'https://nitter.net/search?f=tweets&q=pufpufpafpaf+lang%3Aen'  'https://nitter.net/anthonyfenton'  'https://nitter.net/frank275'  'https://nitter.net/SaRaAshcraft'  'https://nitter.net/LucindDionysius'  'https://nitter.net/boginjaproleca'  'https://nitter.net/n0nmanifest' 'https://nitter.net/jeffreyprather' 'https://therightscoop.com/' 'https://nitter.net/JuliansRum' 'https://nitter.net/Stars4P' 'https://nitter.net/kraken_wood' 
[32728:32728:1209/172110.411662:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
[32731:32747:1209/172111.370291:ERROR:ev_root_ca_metadata.cc(841)] Failed to register OID: 0
[449:1:1209/172118.130579:ERROR:webrtc_sdp.cc(396)] Failed to parse: "a=msid: ". Reason: Missing track ID in msid attribute.
[449:1:1209/172118.131935:ERROR:webrtc_sdp.cc(396)] Failed to parse: "a=msid: ". Reason: Missing track ID in msid attribute.
[449:1:1209/172118.132189:ERROR:webrtc_sdp.cc(396)] Failed to parse: "a=msid: ". Reason: Missing track ID in msid attribute.
[449:1:1209/172118.132410:ERROR:webrtc_sdp.cc(396)] Failed to parse: "a=msid: ". Reason: Missing track ID in msid attribute.
[449:1:1209/172118.132620:ERROR:rtc_peer_connection_handler.cc(2575)] Failed to create native session description. Type: "offer" SDP: "v=0\r\no=- 3097479903649175884 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0\r\na=msid-semantic: WMS\r\nm=application 9 UDP/TLS/RTP/SAVPF 118\r\nc=IN IP4 0.0.0.0\r\nb=AS:30\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:JpYu\r\na=ice-pwd:/sTFEE3rzW38rt8NI20ABN+s\r\na=ice-options:trickle\r\na=fingerprint:sha-256 38:AA:10:C2:44:A6:7E:33:E0:61:50:98:34:CB:6B:D3:CA:36:CE:64:74:98:1C:8B:EF:2F:64:8A:4C:14:6D:93\r\na=setup:actpass\r\na=mid:0\r\na=sendrecv\r\na=msid: \r\na=rtcp-mux\r\na=rtpmap:118 google-data/90000\r\na=ssrc:713266884 cname:xAFwYrx7utD/bNy/\r\na=ssrc:713266884 msid:- \r\na=ssrc:713266884 mslabel:-\r\na=ssrc:713266884 label:\r\n"
[449:1:1209/172118.132747:ERROR:rtc_peer_connection_handler.cc(1367)] "Failed to parse SessionDescription. a=msid:  Missing track ID in msid attribute."
thankGdasuser /opt/ungoogled-chromium_87.0.4280.67-1.1_linux $ 
```
Therefore there were several artefacts in that first retrial:-

**Error 3A:**  Lines 2-3 in the terminal output display the original './chrome-wrapper' command partly rehashed. Maybe this is due to a bug on my system installation, as with the following error.

**Error 3B:**  Line 2 shows the command, but starting with an URL containing the username 'thankGdasuser' in part:
```
 $ ./chrome-wrapper 'https://gnethankGdasuser
```

The prompt, presumably, should be username (`thankGdasuser`), path (`/opt/ungoogled-chromium_87.0.4280.67-1.1_linux`), prompt symbol (`$`), as follows:
```
thankGdasuser /opt/ungoogled-chromium_87.0.4280.67-1.1_linux $
```
Inspecting the output of that first retrial, there were further artefacts:-

**ERROR 3C:**  _'ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.'_

**ERROR 3D:** _'ERROR:ev_root_ca_metadata.cc(841)] Failed to register OID: 0'_

**ERROR 3E:** _'ERROR:webrtc_sdp.cc(396)] Failed to parse: "a=msid: ". Reason: Missing track ID in msid attribute.'_
This occurs four times, sequentially, as shown above.

**ERROR 3F:** _'ERROR:rtc_peer_connection_handler.cc(2575)] Failed to create native session description._

**ERROR 3G:** _'ERROR:rtc_peer_connection_handler.cc(1367)] "Failed to parse SessionDescription. a=msid:  Missing track ID in msid attribute."'_

Seeing how the screenshot was just a slither, I tried to reproduce the error by again removing the .config/chromium settings folder for a clean install.  This second time, a readable screenshot was successful, but somehow only two errors reported:

![github com__Eloston__ungoogled-chromium__issues-PortLin87 0 4280 67-1 1 - Segmentation Fault with v85 settings, Singleton links appear, and four output errors - 9 12 2SSECONDSCREENSHOT](https://user-images.githubusercontent.com/17560937/101701670-5c474700-3a4d-11eb-8716-70671001517b.PNG)

Output from this second retrial:
```
thankGdasuser /opt/ungoogled-chromium_87.0.4280.67-1.1_linux $ ./chrome-wrapper 'https://gnews.org/' 'https://nitter.net/CHHR01'  'https://nitter.net/Stars4P'  'https://nitter.net/roccogalatilaw'  'https://nitter.net/Rothbard1776'  'https://nitter.net/SidneyPowell1' 'https://nitter.net/dmills3710'  'https://nitter.net/iNewsTV' 'https://nitter.net/ElizabetCovfefe' 'https://nitter.net/GeorgWebb' 'https://nitter.net/search?f=tweets&q=pufpufpafpaf+lang%3Aen'  'https://nitter.net/anthonyfenton'  'https://nitter.net/frank275'  'https://nitter.net/SaRaAshcraft'  'https://nitter.net/LucindDionysius'  'https://nitter.net/boginjaproleca'  'https://nitter.net/n0nmanifest' 'https://nitter.net/jeffreyprather' 'https://therightscoop.com/' 'https://nitter.net/JuliansRum' 'https://nitter.net/Stars4P' 'https://nitter.net/kraken_wood' 
[11296:11296:1209/175830.548160:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
[11300:11341:1209/175831.340934:ERROR:ev_root_ca_metadata.cc(841)] Failed to register OID: 0
thankGdasuser /opt/ungoogled-chromium_87.0.4280.67-1.1_linux $ 
```
Therefore, there were only two errors in this second retrial:-
**ERROR 3H:** _'ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.'_

**ERROR 3I:** _'ERROR:ev_root_ca_metadata.cc(841)] Failed to register OID: 0'_

Some UC sessions apparently generate a bit more cooling fan activity than with v85.  
Thank you very much for your work.

**Comment by LordTwix** [comment]
Hi there, jlj2.

I looked into some of the issues you ran into and tried to reproduce them on my end (Debian 10.7, 64-bit):

1. I have not explicitly tried to create a new profile in a version below 87, but I don‘t recall having this problem. If creating a new profile and importing settings from the old one worked for you, I‘d agree with what you said, that your profile may have been corrupted.

2. When I create a 'Default' profile from scratch, add extensions, set some settings and then copy `$HOME/.config/chromium/Default/` to another user, settings and extension are present. Did you copy the folder while running UC? When I look into my `$HOME/.config/chromium/` I don't have any files named Singleton* unless I‘m currently running UC, in which case there are some temporary symlinks named Singleton*.

Regarding 3C/3H:
This seems to be a [general Chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=264818#c39) with GPUs using MESA drivers.

**Comment by jlj2** [comment]
> 1. If creating a new profile and importing settings from the old one worked for you, I‘d agree with what you said, that your profile may have been corrupted.
Using a profile from v85 did not work, as pointed out in section 1).  However, creating a new profile for v87.0.4280.67-1.1 and then exporting them for a new user somehow didn't work other than notably preserving bookmarks, as pointed out in section 2a) above: "Cookie policies, font settings and v87 extensions at least, as set by the first user, somehow did not carry over despite having being set by the first user in a fresh v87 install".

> 2\. When I create a 'Default' profile from scratch, add extensions, set some settings and then copy `$HOME/.config/chromium/Default/` to another user, settings and extension are present. Did you copy the folder while running UC?
Importing the `$HOME/.config/chromium/Default/` directory on its own was never attempted.  Is that a more recommended way to preserve settings, as opposed to attempting to conserve the whole`$HOME/.config/chromium` folder? I won't try that at this point, but I could try it with a future version.  Hopefully that approach might help someone.
No folder was copied while UC was running.

> 2\. When I look into my `$HOME/.config/chromium/` I don't have any files named Singleton* unless I‘m currently running UC, in which case there are some temporary symlinks named Singleton*.
On further observation, that seems to occur with me as well in v87:  Singleton links appear only when running UC v87.



> Regarding 3C/3H:
> This seems to be a [general Chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=264818#c39) with GPUs using MESA drivers.
Thanks for the tip.  Indeed, my notebook's monitor is not running these days and an external monitor is being used.  Maybe MESA is being used therefore. 
I'll leave these observations as they stand, as I may not try to make modifications to this setup.  If anyone wants to improve on them, go ahead, but as far I am concerned, this issue could be closed.

**Comment by jlj2** [comment]
> 1. If creating a new profile and importing settings from the old one worked for you, I‘d agree with what you said, that your profile may have been corrupted.

Creating a new profile for v87.0.4280.67-1.1 and then exporting them for a new user somehow didn't work other than notably preserving bookmarks, as pointed out in section 2a) above: "Cookie policies, font settings and v87 extensions at least, as set by the first user, somehow did not carry over despite having being set by the first user in a fresh v87 install".



> 2\. When I create a 'Default' profile from scratch, add extensions, set some settings and then copy `$HOME/.config/chromium/Default/` to another user, settings and extension are present. Did you copy the folder while running UC?

Importing the `$HOME/.config/chromium/Default/` directory on its own was never attempted.  Is that a more recommended way to preserve settings, as opposed to attempting to conserve the whole `$HOME/.config/chromium` folder? I won't try that at this point, but I may try it with a future version.  Hopefully that approach could help someone.
No folder was copied while UC was running.



> 2\. When I look into my `$HOME/.config/chromium/` I don't have any files named Singleton* unless I‘m currently running UC, in which case there are some temporary symlinks named Singleton*.

On further observation, that seems to occur with me as well in v87:  Singleton links appear only when running UC v87.


> Regarding 3C/3H:
> This seems to be a [general Chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=264818#c39) with GPUs using MESA drivers.

Thanks for the tip.  Indeed, the notebook's monitor is not running these days and an external monitor is being used.  Perhaps that could account for MESA being used, though I don't know. 
I'll leave these observations as they stand, as I may not try to make modifications to this setup.  If anyone wants to improve on them, go ahead, but as far I am concerned, this issue could be closed.

**Comment by Eloston** [comment]
Closing stale issues.
