### ISSUE TITLE
Add libatomic

### ISSUE THREAD

**Issue by oka-netizen4293** [ungoogled-software/ungoogled-chromium-portablelinux#85]
**Description of problem:**
On Fedora 33 (GNOME) it is not possible to start ungoogled-chromium AppImage. Neither in Files nor via Terminal.

**How reproducible:**
Always: the issue is observed each time.

**Steps to Reproduce:**
1. Download ungoogled-chromium AppImage 
https://ungoogled-software.github.io/ungoogled-chromium-binaries/ -> 

Linux AppImage 64-bit -> 87.0.4280.141-1.1 -> 

https://github.com/LordTwix/ungoogled-chromium-binaries/releases/download/87.0.4280.141-1.1/ungoogled-chromium_87.0.4280.141-1.1_linux.AppImage

2. Open GNOME Terminal in Fedora 33 (GNOME) and drag and drop (with the mouse) the ungoogled-chromium AppImage to GNOME Terminal.

3. This output appears in Terminal:

[fedora@localhost ~]$ '/home/fedora/Downloads/ungoogled-chromium_87.0.4280.141-1.1_linux.AppImage' 
/tmp/.mount_ungoogtyZUdM/opt/google/chrome/chrome: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory

**Actual results:**
ungoogled-chromium AppImage cannot be launched.

**Expected results:**
ungoogled-chromium AppImage can be launched just like other AppImage applications.

**Additional info:**
I also tried to install libatomic.so.1 in Terminal.
`[fedora@localhost ~]$ sudo dnf install libatomic.so.1`
 
But the problem remains, the same as what I wrote in Steps to reproduce in point 3.

**Additional info 2:**
Just typed this in the Terminal and it was solved: 

`[fedora@localhost ~]$ sudo dnf install libatomic`

This means that the problem can be fixed automatically for users without additional installation if libatomic is integrated into ungoogled-chromium AppImage.

**Comment by oka-netizen4293** [comment]
@LordTwix
Can you help bundle libatomic into your AppImage?

I as a non-developer don't know how to do it. I hope you can help.

**Comment by LordTwix** [comment]
Hey there ,
I don't know your specific use case, but there is a [repository](https://github.com/ungoogled-software/ungoogled-chromium-fedora#downloads) of Ungoogled-Chromium for Fedora/CentOS available if I'm not mistaken. If you want to use an AppImage, you could (as a quick and intermediate solution) try [this version](https://github.com/LordTwix/ungoogled-chromium-binaries/releases/download/87.0.4280.141-1.1/ungoogled-chromium_87.0.4280.141-1.1+libatomic_linux.AppImage), in which I now additionally integrated libatomic, but I only checked that it starts (at all) on "Fedora 33 Live".

**Comment by Bd954wxadssa** [comment]
> Hey there ,
> I don't know your specific use case, but there is a [repository](https://github.com/ungoogled-software/ungoogled-chromium-fedora#downloads) of Ungoogled-Chromium for Fedora/CentOS available if I'm not mistaken. If you want to use an AppImage, you could (as a quick and intermediate solution) try [this version](https://github.com/LordTwix/ungoogled-chromium-binaries/releases/download/87.0.4280.141-1.1/ungoogled-chromium_87.0.4280.141-1.1+libatomic_linux.AppImage), in which I now additionally integrated libatomic, but I only checked that it starts (at all) on "Fedora 33 Live".

Thank you very much.

I also have the same problem with KDE neon 5.20 and Fedora 32. The new AppImage with libatomic has solved the problem completely and can start ungoogled-chromium from my USB drive. It would be good if libatomic is always integrated in repository.

**Comment by Bd954wxadssa** [comment]
@LordTwix 
Other question works for you quickly switch to another search engine via keyword?

Here what I mean exactly
https://superuser.com/a/1021761

I tape the keyword and space-key but it does not appear with the Ungoogled-Chromium AppImage version, is this a bug or has the feature been removed?

**Comment by LordTwix** [comment]
@Bd954wxadssa 

The binaries were built without any modifications, they should have all the default features of Ungoogled Chromium. I tested the AppImage on the "Fedora 33 Live" image with the newly created profile and the default search engine keywords as well as custom ones were working for me there.

**Comment by Eloston** [comment]
Closing stale issues.
