### ISSUE TITLE
Feature request: Official portable build

### ISSUE THREAD

**Issue by ilu33** [ungoogled-software/ungoogled-chromium-portablelinux#86]
I'm not sure about the right place to put this feature request. Feel free to close the wrong one.

As somebody proposed in discussions having an official portable build to take and repackage in other distros would be nice. It would really help to spread this project. There's at least one distro considering this. Taking the unofficial binaries seems not like something a distro can do as you need to trust more and completely unknown users than just @Eloston. 
Building chromium is a task only major distributions can tackle. Adding ungoogled-chromium-portablelinux to OBS would be perfect. It just needs to stay portable (which means /opt, obviously).

I came to understand that the OBS is operated by @braewoods and @jstkdng. Since Eloston obviously approves this, that would be trustworthy enough, I think.

**Comment by tpo** [comment]
@ilu33 isn't this a duplicat of issue #50 ? Maybe you would like to close this issue in favor of #50 to reduce the chaos? And if necessary comment there?

**Comment by ilu33** [comment]
Closing this in favor of https://github.com/ungoogled-software/ungoogled-chromium-portablelinux/issues/50.
