### ISSUE TITLE
Cannot build tag 87.0.4280.141-1.1 (Ubuntu 18.04, clang 12)

### ISSUE THREAD

**Issue by alpo** [ungoogled-software/ungoogled-chromium-portablelinux#89]
Attempt to build current master using instructuions fails with message:
```
../../third_party/blink/renderer/platform/disk_data_allocator.cc:66:10: error: call to deleted constructor of 'blink::DiskDataMetadata'
  return chosen_chunk;
         ^~~~~~~~~~~~
../../third_party/blink/renderer/platform/disk_data_metadata.h:17:3: note: 'DiskDataMetadata' has been explicitly marked deleted here
  DiskDataMetadata(DiskDataMetadata&& other) = delete;
  ^
1 error generated.
```
Probably was fixed here: https://github.com/chromium/chromium/commit/d62de64e2fd20a4811593cb2248bb476aebfadf5#diff-01cd2432d0e8e0055c79a9f3375aaf213a8be0bbaa63c8396317723e7cc45f72

**Comment by Eloston** [comment]
Tag `90.0.4430.85-1.1` is out, please let me know if you still have this issue.
