### ISSUE TITLE
Automate updates

### ISSUE THREAD

**Issue by Eloston** [ungoogled-software/ungoogled-chromium-portablelinux#91]
Question: Can we automate updates to this repo whenever ungoogled-chromium updates?

Since the amount of changes (patches, build flags, etc.) is relatively small, I suspect we could write a simple GitHub Actions workflow that tries to refresh all the changes. If it fails part-way, maybe we could have it draft a PR that we can continue working on.

It might help keep this repo up-to-date, because I think most of the devs here don't update this repo because it's more work than it's worth (compared to other platform repos).

**Comment by mdedonno1337** [comment]
I'm working at the moment on my gitlab actions to do that.
From a security point of view, I agree that the compilation shall be done here directly to provide the binaries as github actefacts.

I'm working on my side to understand how the super-project and submodules is working, and let you know.

I'm ok, once working on my side, to make a PR and maintaine it.

**Comment by Eloston** [comment]
Resolved in 91c811d09d396465bb7360a0ad0e75cceff459db
