### ISSUE TITLE
Automatic update not working ?

### ISSUE THREAD

**Issue by mdedonno1337** [ungoogled-software/ungoogled-chromium-portablelinux#97]
Hi,

Not sure, but the automatic update of this repo as described in the issue #91 and commit 91c811d09d396465bb7360a0ad0e75cceff459db is probably not working, or I dont understand it.

I thought it was a change on master on https://github.com/Eloston/ungoogled-chromium that should trigger an action here to upate master here with the new tag.
Am I wrong ?

**Comment by Eloston** [comment]
Yeah it's not fully automated yet. I haven't gotten around to creating a Personal Access Token and setting up a workflow on ungoogled-chromium to trigger the workflow here.

**Comment by mdedonno1337** [comment]
haaa ok, perfect in this case. thanks for the work on this !
